import type { LabSettings, TestTemplate, Branch } from '../types/lab';

export const defaultBranches: Branch[] = [
  {
    id: 'branch-01',
    code: 'BR01',
    name: 'Village Rampur Branch (Rural Care)',
    address: 'Opp. Primary Health Center, Rampur Village',
    phone: '+91 98765 11111',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'branch-02',
    code: 'BR02',
    name: 'Tehsil HQ Central Diagnostic Centre',
    address: 'Civil Lines, Tehsil Headquarters Market',
    phone: '+91 98765 22222',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const defaultSettings: LabSettings = {
  id: 'lab_profile',
  currentBranchId: 'branch-01',
  currentBranchCode: 'BR01',
  currentBranchName: 'Village Rampur Branch (Rural Care)',
  labName: 'Aarogya Diagnostic Centre & Clinical Laboratory',
  tagline: 'Precision Diagnostics • Trusted Village Care • Multi-Branch Quality',
  address: 'Main Market Road, Opp. Community Health Center, Tehsil HQ',
  phone: '+91 98765 43210 / +91 91234 56789',
  email: 'aarogyalab.village@gmail.com',
  regNo: 'LAB/DIS/2026/8942',
  pathologistName: 'Dr. Anand M. Patel, M.D. (Pathology)',
  pathologistDegree: 'Consultant Pathologist (Reg No: MCI-54892)',
  technicianName: 'Rameshwar Sharma (DMLT, Senior Lab Tech)',
  currencySymbol: '₹',
  centralServerUrl: 'http://localhost:5000',
  cloudSyncUrl: 'https://tkiznpyammdjelhczwgf.supabase.co',
  cloudSyncKey: 'sb_publishable_VDbah35CkOFp7dxFFK74Rw_x5PjFUgf',
  autoSyncEnabled: true,
  lastSyncedAt: null,
};

export const defaultTests: TestTemplate[] = [
  {
    id: 'test-cbc',
    code: 'CBC',
    name: 'Complete Blood Count (CBC with ESR)',
    category: 'Hematology',
    price: 300,
    sampleType: 'EDTA Whole Blood (2 ml)',
    isActive: true,
    updatedAt: new Date().toISOString(),
    syncStatus: 'pending',
    interpretationNotes: 'Automated 5-part cell counter analysis verified with peripheral blood smear microscopy.',
    parameters: [
      {
        id: 'p-hb',
        name: 'Hemoglobin (Hb)',
        unit: 'g/dL',
        normalRangeMin: 12.0,
        normalRangeMax: 17.0,
        normalRangeText: '13.0 - 17.0 (Male) | 12.0 - 15.0 (Female)',
        genderSpecific: {
          male: { min: 13.0, max: 17.0, text: '13.0 - 17.0' },
          female: { min: 12.0, max: 15.0, text: '12.0 - 15.0' },
        },
      },
      {
        id: 'p-tlc',
        name: 'Total Leukocyte Count (TLC / WBC)',
        unit: '/cumm',
        normalRangeMin: 4000,
        normalRangeMax: 11000,
        normalRangeText: '4,000 - 11,000',
      },
      {
        id: 'p-neutrophils',
        name: 'Neutrophils',
        unit: '%',
        normalRangeMin: 40,
        normalRangeMax: 75,
        normalRangeText: '40 - 75',
      },
      {
        id: 'p-lymphocytes',
        name: 'Lymphocytes',
        unit: '%',
        normalRangeMin: 20,
        normalRangeMax: 45,
        normalRangeText: '20 - 45',
      },
      {
        id: 'p-eosinophils',
        name: 'Eosinophils',
        unit: '%',
        normalRangeMin: 1,
        normalRangeMax: 6,
        normalRangeText: '1 - 6',
      },
      {
        id: 'p-monocytes',
        name: 'Monocytes',
        unit: '%',
        normalRangeMin: 2,
        normalRangeMax: 10,
        normalRangeText: '2 - 10',
      },
      {
        id: 'p-basophils',
        name: 'Basophils',
        unit: '%',
        normalRangeMin: 0,
        normalRangeMax: 1,
        normalRangeText: '0 - 1',
      },
      {
        id: 'p-rbc',
        name: 'Total RBC Count',
        unit: 'million/cumm',
        normalRangeMin: 3.8,
        normalRangeMax: 5.5,
        normalRangeText: '4.5 - 5.5 (Male) | 3.8 - 4.8 (Female)',
        genderSpecific: {
          male: { min: 4.5, max: 5.5, text: '4.5 - 5.5' },
          female: { min: 3.8, max: 4.8, text: '3.8 - 4.8' },
        },
      },
      {
        id: 'p-platelets',
        name: 'Platelet Count',
        unit: 'lakh/cumm',
        normalRangeMin: 1.5,
        normalRangeMax: 4.5,
        normalRangeText: '1.50 - 4.50',
      },
      {
        id: 'p-pcv',
        name: 'PCV / Packed Cell Volume',
        unit: '%',
        normalRangeMin: 36,
        normalRangeMax: 50,
        normalRangeText: '40 - 50 (Male) | 36 - 46 (Female)',
      },
      {
        id: 'p-mcv',
        name: 'MCV',
        unit: 'fL',
        normalRangeMin: 80,
        normalRangeMax: 100,
        normalRangeText: '80 - 100',
      },
      {
        id: 'p-mch',
        name: 'MCH',
        unit: 'pg',
        normalRangeMin: 27,
        normalRangeMax: 32,
        normalRangeText: '27 - 32',
      },
      {
        id: 'p-mchc',
        name: 'MCHC',
        unit: 'g/dL',
        normalRangeMin: 32,
        normalRangeMax: 36,
        normalRangeText: '32 - 36',
      },
      {
        id: 'p-esr',
        name: 'ESR (Westergren Method)',
        unit: 'mm/1st hr',
        normalRangeMin: 0,
        normalRangeMax: 20,
        normalRangeText: '0 - 15 (Male) | 0 - 20 (Female)',
      },
    ],
  },
  {
    id: 'test-glucose',
    code: 'GLU-RBS',
    name: 'Blood Glucose (Random / Fasting / PP)',
    category: 'Biochemistry',
    price: 80,
    sampleType: 'Fluoride Plasma (1 ml)',
    isActive: true,
    updatedAt: new Date().toISOString(),
    syncStatus: 'pending',
    interpretationNotes: 'Fasting: 70-100 mg/dL normal. Post-Prandial < 140 mg/dL normal.',
    parameters: [
      {
        id: 'p-glu-type',
        name: 'Sample Type / Timing',
        unit: '',
        normalRangeText: 'Fasting / Post Prandial / Random',
        options: ['Fasting (10-12 hrs fast)', 'Post Prandial (2 hrs post meal)', 'Random Blood Sugar'],
        defaultValue: 'Random Blood Sugar',
      },
      {
        id: 'p-glu-value',
        name: 'Blood Sugar Level',
        unit: 'mg/dL',
        normalRangeMin: 70,
        normalRangeMax: 140,
        normalRangeText: '70 - 140',
      },
    ],
  },
  {
    id: 'test-lipid',
    code: 'LIPID',
    name: 'Lipid Profile (Cholesterol Panel)',
    category: 'Biochemistry',
    price: 450,
    sampleType: 'Serum (1.5 ml) - 12 Hours Fasting',
    isActive: true,
    updatedAt: new Date().toISOString(),
    syncStatus: 'pending',
    interpretationNotes: 'Desirable: Total Cholesterol < 200 mg/dL, Triglycerides < 150 mg/dL.',
    parameters: [
      {
        id: 'p-chol-total',
        name: 'Total Cholesterol',
        unit: 'mg/dL',
        normalRangeMin: 125,
        normalRangeMax: 200,
        normalRangeText: '< 200 Desirable',
      },
      {
        id: 'p-triglycerides',
        name: 'Serum Triglycerides',
        unit: 'mg/dL',
        normalRangeMin: 50,
        normalRangeMax: 150,
        normalRangeText: '< 150 Normal',
      },
      {
        id: 'p-hdl',
        name: 'HDL (Good Cholesterol)',
        unit: 'mg/dL',
        normalRangeMin: 40,
        normalRangeMax: 60,
        normalRangeText: '> 40 (Male) | > 50 (Female)',
      },
      {
        id: 'p-ldl',
        name: 'LDL (Bad Cholesterol)',
        unit: 'mg/dL',
        normalRangeMin: 50,
        normalRangeMax: 100,
        normalRangeText: '< 100 Optimal',
      },
      {
        id: 'p-vldl',
        name: 'VLDL Cholesterol',
        unit: 'mg/dL',
        normalRangeMin: 10,
        normalRangeMax: 30,
        normalRangeText: '10 - 30',
      },
      {
        id: 'p-chol-ratio',
        name: 'Total / HDL Ratio',
        unit: 'Ratio',
        normalRangeMin: 3.0,
        normalRangeMax: 5.0,
        normalRangeText: '3.0 - 5.0',
      },
    ],
  },
  {
    id: 'test-kft',
    code: 'KFT',
    name: 'Kidney Function Test (KFT / RFT)',
    category: 'Biochemistry',
    price: 400,
    sampleType: 'Serum (2 ml)',
    isActive: true,
    updatedAt: new Date().toISOString(),
    syncStatus: 'pending',
    parameters: [
      {
        id: 'p-urea',
        name: 'Blood Urea',
        unit: 'mg/dL',
        normalRangeMin: 15,
        normalRangeMax: 45,
        normalRangeText: '15.0 - 45.0',
      },
      {
        id: 'p-creatinine',
        name: 'Serum Creatinine',
        unit: 'mg/dL',
        normalRangeMin: 0.6,
        normalRangeMax: 1.3,
        normalRangeText: '0.7 - 1.3 (Male) | 0.5 - 1.1 (Female)',
        genderSpecific: {
          male: { min: 0.7, max: 1.3, text: '0.7 - 1.3' },
          female: { min: 0.5, max: 1.1, text: '0.5 - 1.1' },
        },
      },
      {
        id: 'p-uricacid',
        name: 'Serum Uric Acid',
        unit: 'mg/dL',
        normalRangeMin: 2.6,
        normalRangeMax: 7.2,
        normalRangeText: '3.5 - 7.2 (Male) | 2.6 - 6.0 (Female)',
      },
    ],
  },
  {
    id: 'test-lft',
    code: 'LFT',
    name: 'Liver Function Test (LFT)',
    category: 'Biochemistry',
    price: 550,
    sampleType: 'Serum (2 ml)',
    isActive: true,
    updatedAt: new Date().toISOString(),
    syncStatus: 'pending',
    parameters: [
      {
        id: 'p-bili-tot',
        name: 'Bilirubin Total',
        unit: 'mg/dL',
        normalRangeMin: 0.2,
        normalRangeMax: 1.2,
        normalRangeText: '0.2 - 1.2',
      },
      {
        id: 'p-bili-dir',
        name: 'Bilirubin Direct',
        unit: 'mg/dL',
        normalRangeMin: 0.0,
        normalRangeMax: 0.3,
        normalRangeText: '0.0 - 0.3',
      },
      {
        id: 'p-sgot',
        name: 'SGOT / AST',
        unit: 'U/L',
        normalRangeMin: 10,
        normalRangeMax: 40,
        normalRangeText: '10 - 40',
      },
      {
        id: 'p-sgpt',
        name: 'SGPT / ALT',
        unit: 'U/L',
        normalRangeMin: 10,
        normalRangeMax: 45,
        normalRangeText: '10 - 45',
      },
      {
        id: 'p-alp',
        name: 'Alkaline Phosphatase (ALP)',
        unit: 'U/L',
        normalRangeMin: 30,
        normalRangeMax: 120,
        normalRangeText: '30 - 120',
      },
      {
        id: 'p-protein-tot',
        name: 'Total Serum Protein',
        unit: 'g/dL',
        normalRangeMin: 6.0,
        normalRangeMax: 8.3,
        normalRangeText: '6.0 - 8.3',
      },
      {
        id: 'p-albumin',
        name: 'Serum Albumin',
        unit: 'g/dL',
        normalRangeMin: 3.5,
        normalRangeMax: 5.0,
        normalRangeText: '3.5 - 5.0',
      },
    ],
  },
  {
    id: 'test-urine',
    code: 'URINE-RE',
    name: 'Urine Routine & Microscopic Examination',
    category: 'Clinical Pathology',
    price: 120,
    sampleType: 'Clean Catch Midstream Urine (20 ml)',
    isActive: true,
    updatedAt: new Date().toISOString(),
    syncStatus: 'pending',
    parameters: [
      { id: 'p-u-color', name: 'Color', unit: '', normalRangeText: 'Pale Yellow / Straw', options: ['Pale Yellow', 'Yellow', 'Amber', 'Reddish', 'Straw'], defaultValue: 'Pale Yellow' },
      { id: 'p-u-trans', name: 'Transparency', unit: '', normalRangeText: 'Clear', options: ['Clear', 'Hazy', 'Turbid'], defaultValue: 'Clear' },
      { id: 'p-u-ph', name: 'Reaction / pH', unit: '', normalRangeText: '5.0 - 7.5', options: ['Acidic (5.5)', 'Acidic (6.0)', 'Neutral (7.0)', 'Alkaline (8.0)'], defaultValue: 'Acidic (6.0)' },
      { id: 'p-u-albumin', name: 'Albumin / Protein', unit: '', normalRangeText: 'Nil / Negative', options: ['Nil', 'Trace', '1+ (30 mg/dL)', '2+ (100 mg/dL)', '3+ (300 mg/dL)'], defaultValue: 'Nil' },
      { id: 'p-u-sugar', name: 'Sugar / Glucose', unit: '', normalRangeText: 'Nil / Negative', options: ['Nil', 'Trace', '0.5%', '1%', '2%'], defaultValue: 'Nil' },
      { id: 'p-u-pus', name: 'Pus Cells (WBCs)', unit: '/hpf', normalRangeText: '0 - 4 /hpf', defaultValue: '1 - 2' },
      { id: 'p-u-rbc', name: 'RBCs', unit: '/hpf', normalRangeText: 'Nil', defaultValue: 'Nil' },
      { id: 'p-u-epi', name: 'Epithelial Cells', unit: '/hpf', normalRangeText: 'Few / 1-3', defaultValue: 'Few' },
      { id: 'p-u-casts', name: 'Casts', unit: '', normalRangeText: 'Nil', defaultValue: 'Nil' },
      { id: 'p-u-crystals', name: 'Crystals', unit: '', normalRangeText: 'Nil', defaultValue: 'Nil' },
    ],
  },
  {
    id: 'test-widal',
    code: 'WIDAL',
    name: 'Widal Slide Test (Typhoid Fever)',
    category: 'Serology',
    price: 180,
    sampleType: 'Serum (1 ml)',
    isActive: true,
    updatedAt: new Date().toISOString(),
    syncStatus: 'pending',
    parameters: [
      { id: 'p-w-o', name: 'S. Typhi \'O\' Antigen', unit: 'Titre', normalRangeText: '< 1:80 Negative', options: ['Negative (< 1:80)', '1:80', '1:160 (Positive)', '1:320 (Positive)'], defaultValue: 'Negative (< 1:80)' },
      { id: 'p-w-h', name: 'S. Typhi \'H\' Antigen', unit: 'Titre', normalRangeText: '< 1:80 Negative', options: ['Negative (< 1:80)', '1:80', '1:160 (Positive)', '1:320 (Positive)'], defaultValue: 'Negative (< 1:80)' },
      { id: 'p-w-ah', name: 'S. Paratyphi \'AH\'', unit: 'Titre', normalRangeText: 'Negative (< 1:80)', options: ['Negative (< 1:80)', '1:80', '1:160'], defaultValue: 'Negative (< 1:80)' },
      { id: 'p-w-bh', name: 'S. Paratyphi \'BH\'', unit: 'Titre', normalRangeText: 'Negative (< 1:80)', options: ['Negative (< 1:80)', '1:80', '1:160'], defaultValue: 'Negative (< 1:80)' },
      { id: 'p-w-result', name: 'Final Impression', unit: '', normalRangeText: 'Negative', options: ['Negative for Enteric Fever', 'Positive for Enteric (Typhoid) Fever'], defaultValue: 'Negative for Enteric Fever' },
    ],
  },
  {
    id: 'test-malaria',
    code: 'MALARIA-AG',
    name: 'Malaria Rapid Antigen Test (Pv / Pf)',
    category: 'Serology',
    price: 150,
    sampleType: 'Whole Blood / Fingerprick',
    isActive: true,
    updatedAt: new Date().toISOString(),
    syncStatus: 'pending',
    parameters: [
      { id: 'p-m-pv', name: 'Plasmodium vivax (Pv)', unit: '', normalRangeText: 'Negative', options: ['Negative', 'Positive'], defaultValue: 'Negative' },
      { id: 'p-m-pf', name: 'Plasmodium falciparum (Pf)', unit: '', normalRangeText: 'Negative', options: ['Negative', 'Positive'], defaultValue: 'Negative' },
    ],
  },
  {
    id: 'test-bloodgroup',
    code: 'BG-RH',
    name: 'Blood Grouping & Rh Factor',
    category: 'Hematology',
    price: 100,
    sampleType: 'Whole Blood (1 ml)',
    isActive: true,
    updatedAt: new Date().toISOString(),
    syncStatus: 'pending',
    parameters: [
      { id: 'p-bg', name: 'ABO Blood Group', unit: '', normalRangeText: 'A / B / AB / O', options: ['A Positive', 'A Negative', 'B Positive', 'B Negative', 'O Positive', 'O Negative', 'AB Positive', 'AB Negative'], defaultValue: 'B Positive' },
      { id: 'p-rh', name: 'Rh (D) Factor', unit: '', normalRangeText: 'Positive / Negative', options: ['Positive', 'Negative'], defaultValue: 'Positive' },
    ],
  },
];
